sapl/api/urls.py
from django.conf import settings
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from sapl.api.views import (AutoresPossiveisListView, AutoresProvaveisListView,
                            AutorListView, MateriaLegislativaViewSet,
                            ModelChoiceView, SessaoPlenariaViewSet)

from .apps import AppConfig

app_name = AppConfig.name


router = DefaultRouter()
router.register(r'materia', MateriaLegislativaViewSet)
router.register(r'sessao-plenaria', SessaoPlenariaViewSet)
urlpatterns_router = router.urls

urlpatterns_api = [

    url(r'^autor/provaveis',
        AutoresProvaveisListView.as_view(), name='autores_provaveis_list'),
    url(r'^autor/possiveis',
        AutoresPossiveisListView.as_view(), name='autores_possiveis_list'),

    url(r'^autor', AutorListView.as_view(), name='autor_list'),

    url(r'^model/(?P<content_type>\d+)/(?P<pk>\d*)$',
        ModelChoiceView.as_view(), name='model_list'),

]

if settings.DEBUG:
    urlpatterns_api += [
        url(r'^docs', include('rest_framework_docs.urls')), ]

urlpatterns = [
    url(r'^api/', include(urlpatterns_api)),
    url(r'^api/', include(urlpatterns_router))
]

sapl/base/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import (password_reset, password_reset_complete,
                                       password_reset_confirm,
                                       password_reset_done)
from django.views.generic.base import TemplateView

from sapl.base.views import AutorCrud, ConfirmarEmailView, TipoAutorCrud
from sapl.settings import EMAIL_SEND_USER

from .apps import AppConfig
from .forms import LoginForm, NovaSenhaForm, RecuperarSenhaForm
from .views import (AlterarSenha, AppConfigCrud, CasaLegislativaCrud,
                    CreateUsuarioView, DeleteUsuarioView, EditUsuarioView,
                    HelpTopicView, ListarUsuarioView, RelatorioAtasView,
                    RelatorioDataFimPrazoTramitacaoView,
                    RelatorioHistoricoTramitacaoView,
                    RelatorioMateriasPorAnoAutorTipoView,
                    RelatorioMateriasPorAutorView,
                    RelatorioMateriasTramitacaoView,
                    RelatorioPresencaSessaoView, SaplSearchView)

app_name = AppConfig.name

admin_user = [
    url(r'^sistema/usuario/$', ListarUsuarioView.as_view(), name='user_list'),
    url(r'^sistema/usuario/create$', CreateUsuarioView.as_view(), name='user_create'),
    url(r'^sistema/usuario/(?P<pk>\d+)/edit$', EditUsuarioView.as_view(), name='user_edit'),
    url(r'^sistema/usuario/(?P<pk>\d+)/delete$', DeleteUsuarioView.as_view(), name='user_delete')
]

alterar_senha = [
    url(r'^sistema/alterar-senha/$',
        AlterarSenha.as_view(),
        name='alterar_senha'),

]

recuperar_senha = [
    url(r'^recuperar-senha/email/$',
        password_reset,
        {'post_reset_redirect': 'sapl.base:recuperar_senha_finalizado',
         'email_template_name': 'base/recuperar_senha_email.html',
         'html_email_template_name': 'base/recuperar_senha_email.html',
         'template_name': 'base/recuperar_senha_email_form.html',
         'from_email': EMAIL_SEND_USER,
         'password_reset_form': RecuperarSenhaForm},
        name='recuperar_senha_email'),

    url(r'^recuperar-senha/finalizado/$',
        password_reset_done,
        {'template_name': 'base/recupera_senha_email_enviado.html'},
        name='recuperar_senha_finalizado'),

    url(r'^recuperar-senha/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': 'sapl.base:recuperar_senha_completo',
         'template_name': 'base/nova_senha_form.html',
         'set_password_form': NovaSenhaForm},
        name='recuperar_senha_confirma'),

    url(r'^recuperar-senha/completo/$',
        password_reset_complete,
        {'template_name': 'base/recuperar_senha_completo.html'},
        name='recuperar_senha_completo'),
]


urlpatterns = [
    url(r'^sistema/autor/tipo/', include(TipoAutorCrud.get_urls())),
    url(r'^sistema/autor/', include(AutorCrud.get_urls())),

    url(r'^sistema/ajuda/(?P<topic>\w+)$',
        HelpTopicView.as_view(), name='help_topic'),
    url(r'^sistema/ajuda/$', TemplateView.as_view(template_name='ajuda.html'),
        name='help'),
    url(r'^sistema/casa-legislativa/', include(CasaLegislativaCrud.get_urls()),
        name="casa_legislativa"),
    url(r'^sistema/app-config/', include(AppConfigCrud.get_urls())),

    # TODO mover estas telas para a app 'relatorios'
    url(r'^sistema/relatorios/$', TemplateView.as_view(
        template_name='base/relatorios_list.html'), name='relatorios_list'),
    url(r'^sistema/relatorios/materia-por-autor$',
        RelatorioMateriasPorAutorView.as_view(), name='materia_por_autor'),
    url(r'^sistema/relatorios/materia-por-ano-autor-tipo$',
        RelatorioMateriasPorAnoAutorTipoView.as_view(),
        name='materia_por_ano_autor_tipo'),
    url(r'^sistema/relatorios/materia-por-tramitacao$',
        RelatorioMateriasTramitacaoView.as_view(),
        name='materia_por_tramitacao'),
    url(r'^sistema/relatorios/historico-tramitacoes$',
        RelatorioHistoricoTramitacaoView.as_view(),
        name='historico_tramitacoes'),
    url(r'^sistema/relatorios/data-fim-prazo-tramitacoes$',
        RelatorioDataFimPrazoTramitacaoView.as_view(),
        name='data_fim_prazo_tramitacoes'),
    url(r'^sistema/relatorios/presenca$',
        RelatorioPresencaSessaoView.as_view(),
        name='presenca_sessao'),
    url(r'^sistema/relatorios/atas$',
        RelatorioAtasView.as_view(),
        name='atas'),

    url(r'^email/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        ConfirmarEmailView.as_view(), name='confirmar_email'),


    # todos os sublinks de sistema devem vir acima deste
    url(r'^sistema/$', permission_required('base.view_tabelas_auxiliares')
        (TemplateView.as_view(template_name='sistema.html')),
        name='sistema'),

    url(r'^login/$', views.login, {
        'template_name': 'base/login.html', 'authentication_form': LoginForm},
        name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}, name='logout'),

    url(r'^sistema/search/', SaplSearchView(), name='haystack_search'),

] + recuperar_senha + alterar_senha + admin_user

sapl/crud/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('stub_app.urls')),
]

sapl/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView
from django.views.static import serve as view_static_server

import sapl.api.urls
import sapl.base.urls
import sapl.comissoes.urls
import sapl.compilacao.urls
import sapl.lexml.urls
import sapl.materia.urls
import sapl.norma.urls
import sapl.painel.urls
import sapl.parlamentares.urls
import sapl.protocoloadm.urls
import sapl.redireciona_urls.urls
import sapl.relatorios.urls
import sapl.sessao.urls
import sapl.audiencia.urls

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='sapl_index'),
    url(r'^message$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include(sapl.comissoes.urls)),
    url(r'', include(sapl.sessao.urls)),
    url(r'', include(sapl.parlamentares.urls)),
    url(r'', include(sapl.materia.urls)),
    url(r'', include(sapl.norma.urls)),
    url(r'', include(sapl.lexml.urls)),
    url(r'', include(sapl.painel.urls)),
    url(r'', include(sapl.protocoloadm.urls)),
    url(r'', include(sapl.compilacao.urls)),
    url(r'', include(sapl.relatorios.urls)),
    url(r'', include(sapl.audiencia.urls)),

    # must come at the end
    #   so that base /sistema/ url doesn't capture its children
    url(r'', include(sapl.base.urls)),

    url(r'', include(sapl.api.urls)),

    url(r'^favicon\.ico$', RedirectView.as_view(
        url='/static/img/favicon.ico', permanent=True)),

    # Folhas XSLT e extras referenciadas por documentos migrados do sapl 2.5
    url(r'^XSLT/HTML/(?P<path>.*)$', RedirectView.as_view(
        url='/static/XSLT/HTML/%(path)s', permanent=False)),
    url(r'', include(sapl.redireciona_urls.urls)),
]


# Fix a static asset finding error on Django 1.9 + gunicorn:
# http://stackoverflow.com/questions/35510373/

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', view_static_server, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

painel/models.py
'''
  This file is part of SAPL.
  Copyright (C) 2016 Interlegis
'''
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Painel(models.Model):
    PAINEL_TYPES = (
        ('C', 'Completo'),
        ('P', 'Parlamentares'),
        ('V', 'Votação'),
        ('M', 'Mensagem'),
    )

    aberto = models.BooleanField(verbose_name=_('Abrir painel'), default=False)
    data_painel = models.DateField(verbose_name=_('Data painel'))
    mostrar = models.CharField(max_length=1,
                               choices=PAINEL_TYPES, default='C')

    def __str__(self):
        return str(self.aberto) + ":" + self.data_painel.strftime("%d/%m/%Y")


class Cronometro(models.Model):
    CRONOMETRO_TYPES = (
        ('A', _('Aparte')),
        ('D', _('Discurso')),
        ('O', _('Ordem do dia'))
    )

    CRONOMETRO_STATUS = (
        ('I', 'Start'),
        ('R', 'Reset'),
        ('S', 'Stop'),
    )

    status = models.CharField(
        max_length=1,
        verbose_name=_('Status do cronômetro'),
        choices=CRONOMETRO_STATUS,
        default='S')
    data_cronometro = models.DateField(verbose_name=_('Data do cronômetro'))
    tipo = models.CharField(
        max_length=1, choices=CRONOMETRO_TYPES,
        verbose_name=_('Tipo Cronômetro'))

sapl/audiencia/models.py
import reversion
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from sapl.materia.models import MateriaLegislativa
from sapl.parlamentares.models import (CargoMesa, Parlamentar)

from sapl.utils import (YES_NO_CHOICES, SaplGenericRelation,
                        restringe_tipos_de_arquivo_txt, texto_upload_path)


def get_audiencia_media_path(instance, subpath, filename):
    return './sapl/audiencia/%s/%s/%s' % (instance.numero, subpath, filename)


def pauta_upload_path(instance, filename):
    return texto_upload_path(
        instance, filename, subpath='pauta', pk_first=True)


def ata_upload_path(instance, filename):
    return texto_upload_path(instance, filename, subpath='ata', pk_first=True)


def anexo_upload_path(instance, filename):
    return texto_upload_path(
        instance, filename, subpath='anexo', pk_first=True)


@reversion.register()
class TipoAudienciaPublica(models.Model):
    TIPO_AUDIENCIA_CHOICES = Choices(('A', 'audiencia', _('Audiência Pública')),
                                     ('P', 'plebiscito', _('Plebiscito')),
                                     ('R', 'referendo', _('Referendo')),
                                     ('I', 'iniciativa', _('Iniciativa Popular')))

    nome = models.CharField(
        max_length=50, verbose_name=_('Nome do Tipo de Audiência Pública'), default='Audiência Pública')
    tipo = models.CharField(
        max_length=1, verbose_name=_('Tipo de Audiência Pública'), choices=TIPO_AUDIENCIA_CHOICES, default='A')


    class Meta:
        verbose_name = _('Tipo de Audiência Pública')
        verbose_name_plural = _('Tipos de Audiência Pública')
        ordering = ['nome']

    def __str__(self):
        return self.nome


@reversion.register()
class AudienciaPublica(models.Model):
    materia = models.ForeignKey(
        MateriaLegislativa,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_('Matéria Legislativa'))
    tipo = models.ForeignKey(TipoAudienciaPublica,
                             on_delete=models.PROTECT,
                             null=True,
                             blank=True,
                             verbose_name=_('Tipo de Audiência Pública'))
    numero = models.PositiveIntegerField(blank=True, verbose_name=_('Número'))
    nome = models.CharField(
        max_length=100, verbose_name=_('Nome da Audiência Pública'))
    tema = models.CharField(
        max_length=100, verbose_name=_('Tema da Audiência Pública'))
    data = models.DateField(verbose_name=_('Data'))
    hora_inicio = models.CharField(
        max_length=5, verbose_name=_('Horário Início(hh:mm)'))
    hora_fim = models.CharField(
        max_length=5, verbose_name=_('Horário Fim(hh:mm)'))
    observacao = models.TextField(
        max_length=500, blank=True, verbose_name=_('Observação'))
    audiencia_cancelada = models.BooleanField(
        default=False,
        choices=YES_NO_CHOICES,
        verbose_name=_('Audiência Cancelada?'))
    url_audio = models.URLField(
        max_length=150, blank=True,
        verbose_name=_('URL Arquivo Áudio (Formatos MP3 / AAC)'))
    url_video = models.URLField(
        max_length=150, blank=True,
        verbose_name=_('URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'))
    upload_pauta = models.FileField(
        blank=True,
        null=True,
        upload_to=pauta_upload_path,
        verbose_name=_('Pauta da Audiência Pública'),
        validators=[restringe_tipos_de_arquivo_txt])
    upload_ata = models.FileField(
        blank=True,
        null=True,
        upload_to=ata_upload_path,
        verbose_name=_('Ata da Audiência Pública'),
        validators=[restringe_tipos_de_arquivo_txt])
    upload_anexo = models.FileField(
        blank=True,
        null=True,
        upload_to=anexo_upload_path,
        verbose_name=_('Anexo da Audiência Pública'))

    class Meta:
        verbose_name = _('Audiência Pública')
        verbose_name_plural = _('Audiências Públicas')
        ordering = ['nome', 'numero', 'tipo']

    def __str__(self):
        return self.nome

    def delete(self, using=None, keep_parents=False):
        if self.upload_pauta:
            self.upload_pauta.delete()

        if self.upload_ata:
            self.upload_ata.delete()

        if self.upload_anexo:
            self.upload_anexo.delete()

        return models.Model.delete(
            self, using=using, keep_parents=keep_parents)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if not self.pk and (self.upload_pauta or self.upload_ata or
                            self.upload_anexo):
            upload_pauta = self.upload_pauta
            upload_ata = self.upload_ata
            upload_anexo = self.upload_anexo
            self.upload_pauta = None
            self.upload_ata = None
            self.upload_anexo = None
            models.Model.save(self, force_insert=force_insert,
                              force_update=force_update,
                              using=using,
                              update_fields=update_fields)

            self.upload_pauta = upload_pauta
            self.upload_ata = upload_ata
            self.upload_anexo = upload_anexo

        return models.Model.save(self, force_insert=force_insert,
                                 force_update=force_update,
                                 using=using,
                                 update_fields=update_fields)

sapl/lexml/models.py
import reversion
from django.db import models
from django.utils.translation import ugettext_lazy as _


@reversion.register()
class LexmlProvedor(models.Model):  # LexmlRegistroProvedor
    id_provedor = models.PositiveIntegerField(verbose_name=_('Id do provedor'))
    nome = models.CharField(max_length=255, verbose_name=_('Nome do provedor'))
    sigla = models.CharField(max_length=15)
    email_responsavel = models.EmailField(
        max_length=50,
        blank=True,
        verbose_name=_('E-mail do responsável'))
    nome_responsavel = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_('Nome do responsável'))
    tipo = models.CharField(max_length=50)
    id_responsavel = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_('Id do responsável'))
    xml = models.TextField(
        blank=True,
        verbose_name=_('XML fornecido pela equipe do LexML:'))

    class Meta:
        verbose_name = _('Provedor Lexml')
        verbose_name_plural = _('Provedores Lexml')

    def __str__(self):
        return self.nome


@reversion.register()
class LexmlPublicador(models.Model):
    id_publicador = models.PositiveIntegerField(
        verbose_name=_('Id do publicador'))
    nome = models.CharField(
        max_length=255, verbose_name=_('Nome do publicador'))
    email_responsavel = models.EmailField(
        max_length=50,
        blank=True,
        verbose_name=_('E-mail do responsável'))
    sigla = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_('Sigla do Publicador'))
    nome_responsavel = models.CharField(
        max_length=255,
        blank=True,
        verbose_name=_('Nome do responsável'))
    tipo = models.CharField(max_length=50)
    id_responsavel = models.PositiveIntegerField(
        verbose_name=_('Id do responsável'))

    class Meta:
        verbose_name = _('Publicador Lexml')
        verbose_name_plural = _('Publicadores Lexml')

    def __str__(self):
        return self.nome

sapl/relatorios/models.py
# from django.db import models

# Create your models here.

sapl/templates/sessao/adicionar_varias_materias_ordem.html
{% extends "sessao/adicionar_varias_materias_expediente.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block buttons %}

      {% if filter_url and not filter.form.errors %}

            <div class="actions btn-group pull-right" role="group">
              <a href="{% url 'sapl.sessao:adicionar_varias_materias_ordem_dia' pk_sessao %}" class="btn btn-default">{% trans 'Fazer nova pesquisa' %}</a>
            </div>

            <div class="actions btn-group pull-right" role="group">
              <a href="{% url 'sapl.sessao:ordemdia_list' pk_sessao %}" class="btn btn-default">{% trans 'Matérias da Ordem do Dia' %}</a>
            </div>

      {% endif %}

    {% endblock %}

sapl/templates/sessao/expediente.html
{% extends "crud/detail.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block actions %}{% endblock %}

{% block detail_content %}

{% if perms|get_add_perm:view %}
	{% if expedientes|length == 0 %}
		<div class="alert alert-danger alert-dismissible fade in" role="alert">
			Não há nenhum expediente cadastrado. <br />
			Cique <a href="{% url 'sapl.sessao:tipoexpediente_create'%}">aqui</a> para cadastrar um novo.
		</div>
	{% else %}
		<form method="post">
			{% csrf_token %}

			{% for e in expedientes %}
				<fieldset class="form-group">
					<legend>{{e.tipo}}</legend>
					<input type="hidden" name="tipo" id="tipo" value="{{e.tipo.id}}" class="form-control"/>
					<textarea rows="5" cols="50" name="conteudo" id="conteudo" class="form-control">{{e.conteudo}}</textarea>
					<br />
				</fieldset>
			{% endfor %}

			<br />
			<input type="submit" value="Salvar" class="btn btn-primary"/>
		</form>
	{% endif %}

{% else %}

	{% for e in expedientes %}
			<fieldset class="form-group">
				<legend>{{e.tipo}}</legend>
				<textarea rows="5" cols="50" name="conteudo" id="conteudo" class="form-control">{{e.conteudo}}</textarea>
				<br />
			</fieldset>
	{% endfor %}

{% endif %}

{% endblock detail_content %}
<!-- Texto RICO -->
{% block extra_js %}
	{% if perms|get_add_perm:view %}
		<script language="JavaScript">
			initTinymce(null);
		</script>
	<!-- Se nao tiver permissao, o texto rico fica readonly -->
	{% else %}
		<script language="JavaScript">
			initTinymce(null, true);
		</script>
	{% endif %}
{% endblock %}

sapl/templates/sessao/expedientemateria_form.html
{% extends "crud/form.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block extra_js %}

<script language="Javascript">
  document.getElementById("id_observacao").readOnly = true;

  function recuperar_materia() {
    var tipo_materia = $("#id_tipo_materia").val()
    var numero_materia = $("#id_numero_materia").val()
    var ano_materia = $("#id_ano_materia").val()

    if (tipo_materia && numero_materia && ano_materia) {
      $.get("/sessao/recuperar-materia",{tipo_materia: tipo_materia,
                                  numero_materia: numero_materia,
                                  ano_materia: ano_materia},
                                function(data, status) {
                                  $("#id_observacao").val(data.ementa);
                                });
    }
  }
  var fields = ["#id_tipo_materia", "#id_numero_materia", "#id_ano_materia"]
  for (i = 0; i < fields.length; i++) {
    $(fields[i]).change(recuperar_materia);
  }
</script>

{% endblock %}

sapl/templates/sessao/resumo_ordenacao.html
{% extends "crud/form.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}
<h1 class="page-header">Ordenação do Resumo</h1>
{% endblock %}

{% block base_content %}

{% crispy form %}

{% endblock %}

sapl/templates/sessao/sessaoplenaria_filter.html
{% extends "crud/detail.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block actions %}
  <div class="actions btn-group pull-right" role="group">
    {% if perms.sessao %}
      <a href="{% url 'sapl.sessao:sessaoplenaria_create' %}" class="btn btn-default">
        {% blocktrans with verbose_name=view.verbose_name %} Adicionar Sessão Plenária {% endblocktrans %}
    {% endif %}
    </a>
  </div>
{% endblock %}

{% block detail_content %}
  {% crispy filter.form %}

  {% if show_results %}
    <p></p>
    <table class="table table-striped table-hover">
      <thead class="thead-default"><tr><td><h3>Resultados</h3></td></tr></thead>
      {% if page_obj|length %}
        {% if numero_res > 1 %}
          <h3>Foram encontradas {{numero_res}} sessões.</h3></br>
        {% elif numero_res == 1 %}
          <h3>Foi encontrada {{numero_res}} sessão.</h3></br>
        {% endif %}

        {% for s in page_obj %}
          <tr>
            <td>
              <strong><a href="{% url 'sapl.sessao:sessaoplenaria_detail' s.id %}">{{s}}</strong></a></br>
              <strong>Abertura:</strong> {{s.data_inicio}}</br>
              <strong>Legislatura:</strong> {{s.legislatura}}</br>
              <strong>Sessão Legislativa:</strong> {{s.sessao_legislativa}}</br>
              <strong>Tipo:</strong> {{s.tipo}}</br>
            </td>
          </tr>
        {% endfor %}
      {% else  %}
        <tr><td><h3>Nenhuma Sessão Plenária encontrada com essas especificações</h3></tr>
      {% endif %}
    </table>
    {% include "paginacao.html" %}
  {% endif %}
{% endblock detail_content %}
{% block table_content %}
{% endblock table_content %}


{% block extra_js %}

<script type="text/javascript">
  var querystring = "{{filter_url|safe}}"

  // Esse IF garante que já existe uma querystring, ou seja, algo já foi pesquisado
  if(querystring.length != 0){ 
    $('#id_data_inicio__year').on({
      change: function(){
        window.location.search = jQuery.query.set("data_inicio__year", $('#id_data_inicio__year').val());
      }
    })

    $('#id_data_inicio__month').on({
      change: function(){
        window.location.search = jQuery.query.set("data_inicio__month", $('#id_data_inicio__month').val());
      }
    })

    $('#id_data_inicio__day').on({
      change: function(){
        window.location.search = jQuery.query.set("data_inicio__day", $('#id_data_inicio__day').val());
      }
    })

    $('#id_tipo').on({
      change: function(){
        window.location.search = jQuery.query.set("tipo", $('#id_tipo').val());
      }
    })
  }


</script>

{% endblock %}

sapl/templates/sessao/sessaoplenaria_form.html
{% extends "crud/form.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block extra_js %}

<script language="Javascript">

  // Seleciona o numero de acordo com o tipo
  function recuperar_numero_sessao() {
    var tipo = $("#id_tipo").val()
    var sessao = $("#id_sessao_legislativa").val()

    if (tipo) {
      $.get("/sessao/recuperar-numero-sessao",{tipo: tipo, sessao_legislativa:sessao},
                                      function(data, status) {
                                        $("#id_numero").val(data.numero);
                                        console.log(data)
                                      });
    }
    else{
      $("#id_numero").val('');
    }
  }
  $("#id_tipo").click(recuperar_numero_sessao);
  $("#id_sessao_legislativa").click(recuperar_numero_sessao);


  // Filtra as choices de sessao legislativa pela legislatura
  $(function() {

    function altera_legislatura(){
      var id_legislatura = $("#id_legislatura").val();
      var id_sessao_leg = $("#id_sessao_legislativa").val();
      $("#id_sessao_legislativa option").remove();
      if (id_legislatura) {
          $.get("/sessao/sessao-legislativa-legislatura-ajax", {legislatura: id_legislatura}, function(data) {
              lista_sessoes = data['sessao_legislativa'];

              $('#id_sessao_legislativa').append('<option value="">' + '---------' + '</option>');
              for (i = 0; i < lista_sessoes.length; i++) {
                  $('#id_sessao_legislativa').append('<option value="' + lista_sessoes[i][0] + '">' + lista_sessoes[i][1] + '</option>');
              }
              $("#id_sessao_legislativa").val(id_sessao_leg);
          });
      }
      else{
        $("#id_sessao_legislativa option").remove();
      }
    }

    $("#id_legislatura").ready(altera_legislatura);

    $("#id_legislatura").change(altera_legislatura);
  });

</script>

{% endblock %}

sapl/templates/sessao/sessaoplenaria_list.html
{% extends "crud/list.html" %}
{% load i18n %}
{% block more_buttons %}
  <a href="{% url 'sapl.sessao:pesquisar_sessao' %}" class="btn btn-default">
    {% blocktrans with verbose_name=view.verbose_name %} Pesquisar {{ verbose_name }} {% endblocktrans %}
  </a>
{% endblock %}