sapl/api/urls.py
from django.conf import settings
from django.conf.urls import include, url
from rest_framework.routers import DefaultRouter

from sapl.api.views import (AutoresPossiveisListView, AutoresProvaveisListView,
                            AutorListView, MateriaLegislativaViewSet,
                            ModelChoiceView, SessaoPlenariaViewSet)

from .apps import AppConfig

app_name = AppConfig.name


router = DefaultRouter()
router.register(r'materia', MateriaLegislativaViewSet)
router.register(r'sessao-plenaria', SessaoPlenariaViewSet)
urlpatterns_router = router.urls

urlpatterns_api = [

    url(r'^autor/provaveis',
        AutoresProvaveisListView.as_view(), name='autores_provaveis_list'),
    url(r'^autor/possiveis',
        AutoresPossiveisListView.as_view(), name='autores_possiveis_list'),

    url(r'^autor', AutorListView.as_view(), name='autor_list'),

    url(r'^model/(?P<content_type>\d+)/(?P<pk>\d*)$',
        ModelChoiceView.as_view(), name='model_list'),

]

if settings.DEBUG:
    urlpatterns_api += [
        url(r'^docs', include('rest_framework_docs.urls')), ]

urlpatterns = [
    url(r'^api/', include(urlpatterns_api)),
    url(r'^api/', include(urlpatterns_router))
]

sapl/base/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.views import (password_reset, password_reset_complete,
                                       password_reset_confirm,
                                       password_reset_done)
from django.views.generic.base import TemplateView

from sapl.base.views import AutorCrud, ConfirmarEmailView, TipoAutorCrud
from sapl.settings import EMAIL_SEND_USER

from .apps import AppConfig
from .forms import LoginForm, NovaSenhaForm, RecuperarSenhaForm
from .views import (AlterarSenha, AppConfigCrud, CasaLegislativaCrud,
                    CreateUsuarioView, DeleteUsuarioView, EditUsuarioView,
                    HelpTopicView, ListarUsuarioView, RelatorioAtasView,
                    RelatorioDataFimPrazoTramitacaoView,
                    RelatorioHistoricoTramitacaoView,
                    RelatorioMateriasPorAnoAutorTipoView,
                    RelatorioMateriasPorAutorView,
                    RelatorioMateriasTramitacaoView,
                    RelatorioPresencaSessaoView, SaplSearchView)

app_name = AppConfig.name

admin_user = [
    url(r'^sistema/usuario/$', ListarUsuarioView.as_view(), name='user_list'),
    url(r'^sistema/usuario/create$', CreateUsuarioView.as_view(), name='user_create'),
    url(r'^sistema/usuario/(?P<pk>\d+)/edit$', EditUsuarioView.as_view(), name='user_edit'),
    url(r'^sistema/usuario/(?P<pk>\d+)/delete$', DeleteUsuarioView.as_view(), name='user_delete')
]

alterar_senha = [
    url(r'^sistema/alterar-senha/$',
        AlterarSenha.as_view(),
        name='alterar_senha'),

]

recuperar_senha = [
    url(r'^recuperar-senha/email/$',
        password_reset,
        {'post_reset_redirect': 'sapl.base:recuperar_senha_finalizado',
         'email_template_name': 'base/recuperar_senha_email.html',
         'html_email_template_name': 'base/recuperar_senha_email.html',
         'template_name': 'base/recuperar_senha_email_form.html',
         'from_email': EMAIL_SEND_USER,
         'password_reset_form': RecuperarSenhaForm},
        name='recuperar_senha_email'),

    url(r'^recuperar-senha/finalizado/$',
        password_reset_done,
        {'template_name': 'base/recupera_senha_email_enviado.html'},
        name='recuperar_senha_finalizado'),

    url(r'^recuperar-senha/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        password_reset_confirm,
        {'post_reset_redirect': 'sapl.base:recuperar_senha_completo',
         'template_name': 'base/nova_senha_form.html',
         'set_password_form': NovaSenhaForm},
        name='recuperar_senha_confirma'),

    url(r'^recuperar-senha/completo/$',
        password_reset_complete,
        {'template_name': 'base/recuperar_senha_completo.html'},
        name='recuperar_senha_completo'),
]


urlpatterns = [
    url(r'^sistema/autor/tipo/', include(TipoAutorCrud.get_urls())),
    url(r'^sistema/autor/', include(AutorCrud.get_urls())),

    url(r'^sistema/ajuda/(?P<topic>\w+)$',
        HelpTopicView.as_view(), name='help_topic'),
    url(r'^sistema/ajuda/$', TemplateView.as_view(template_name='ajuda.html'),
        name='help'),
    url(r'^sistema/casa-legislativa/', include(CasaLegislativaCrud.get_urls()),
        name="casa_legislativa"),
    url(r'^sistema/app-config/', include(AppConfigCrud.get_urls())),

    # TODO mover estas telas para a app 'relatorios'
    url(r'^sistema/relatorios/$', TemplateView.as_view(
        template_name='base/relatorios_list.html'), name='relatorios_list'),
    url(r'^sistema/relatorios/materia-por-autor$',
        RelatorioMateriasPorAutorView.as_view(), name='materia_por_autor'),
    url(r'^sistema/relatorios/materia-por-ano-autor-tipo$',
        RelatorioMateriasPorAnoAutorTipoView.as_view(),
        name='materia_por_ano_autor_tipo'),
    url(r'^sistema/relatorios/materia-por-tramitacao$',
        RelatorioMateriasTramitacaoView.as_view(),
        name='materia_por_tramitacao'),
    url(r'^sistema/relatorios/historico-tramitacoes$',
        RelatorioHistoricoTramitacaoView.as_view(),
        name='historico_tramitacoes'),
    url(r'^sistema/relatorios/data-fim-prazo-tramitacoes$',
        RelatorioDataFimPrazoTramitacaoView.as_view(),
        name='data_fim_prazo_tramitacoes'),
    url(r'^sistema/relatorios/presenca$',
        RelatorioPresencaSessaoView.as_view(),
        name='presenca_sessao'),
    url(r'^sistema/relatorios/atas$',
        RelatorioAtasView.as_view(),
        name='atas'),

    url(r'^email/validate/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        '(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})$',
        ConfirmarEmailView.as_view(), name='confirmar_email'),


    # todos os sublinks de sistema devem vir acima deste
    url(r'^sistema/$', permission_required('base.view_tabelas_auxiliares')
        (TemplateView.as_view(template_name='sistema.html')),
        name='sistema'),

    url(r'^login/$', views.login, {
        'template_name': 'base/login.html', 'authentication_form': LoginForm},
        name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}, name='logout'),

    url(r'^sistema/search/', SaplSearchView(), name='haystack_search'),

] + recuperar_senha + alterar_senha + admin_user

sapl/crud/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'', include('stub_app.urls')),
]

sapl/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView
from django.views.static import serve as view_static_server

import sapl.api.urls
import sapl.base.urls
import sapl.comissoes.urls
import sapl.compilacao.urls
import sapl.lexml.urls
import sapl.materia.urls
import sapl.norma.urls
import sapl.painel.urls
import sapl.parlamentares.urls
import sapl.protocoloadm.urls
import sapl.redireciona_urls.urls
import sapl.relatorios.urls
import sapl.sessao.urls
import sapl.audiencia.urls

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'),
        name='sapl_index'),
    url(r'^message$', TemplateView.as_view(template_name='base.html')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'', include(sapl.comissoes.urls)),
    url(r'', include(sapl.sessao.urls)),
    url(r'', include(sapl.parlamentares.urls)),
    url(r'', include(sapl.materia.urls)),
    url(r'', include(sapl.norma.urls)),
    url(r'', include(sapl.lexml.urls)),
    url(r'', include(sapl.painel.urls)),
    url(r'', include(sapl.protocoloadm.urls)),
    url(r'', include(sapl.compilacao.urls)),
    url(r'', include(sapl.relatorios.urls)),
    url(r'', include(sapl.audiencia.urls)),

    # must come at the end
    #   so that base /sistema/ url doesn't capture its children
    url(r'', include(sapl.base.urls)),

    url(r'', include(sapl.api.urls)),

    url(r'^favicon\.ico$', RedirectView.as_view(
        url='/static/img/favicon.ico', permanent=True)),

    # Folhas XSLT e extras referenciadas por documentos migrados do sapl 2.5
    url(r'^XSLT/HTML/(?P<path>.*)$', RedirectView.as_view(
        url='/static/XSLT/HTML/%(path)s', permanent=False)),
    url(r'', include(sapl.redireciona_urls.urls)),
]


# Fix a static asset finding error on Django 1.9 + gunicorn:
# http://stackoverflow.com/questions/35510373/

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += [
        url(r'^media/(?P<path>.*)$', view_static_server, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

sapl/audiencia/models.py
import reversion
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from sapl.materia.models import MateriaLegislativa
from sapl.parlamentares.models import (CargoMesa, Parlamentar)

from sapl.utils import (YES_NO_CHOICES, SaplGenericRelation,
                        restringe_tipos_de_arquivo_txt, texto_upload_path)


def get_audiencia_media_path(instance, subpath, filename):
    return './sapl/audiencia/%s/%s/%s' % (instance.numero, subpath, filename)


def pauta_upload_path(instance, filename):
    return texto_upload_path(
        instance, filename, subpath='pauta', pk_first=True)


def ata_upload_path(instance, filename):
    return texto_upload_path(instance, filename, subpath='ata', pk_first=True)


def anexo_upload_path(instance, filename):
    return texto_upload_path(
        instance, filename, subpath='anexo', pk_first=True)


@reversion.register()
class TipoAudienciaPublica(models.Model):
    TIPO_AUDIENCIA_CHOICES = Choices(('A', 'audiencia', _('Audiência Pública')),
                                     ('P', 'plebiscito', _('Plebiscito')),
                                     ('R', 'referendo', _('Referendo')),
                                     ('I', 'iniciativa', _('Iniciativa Popular')))

    nome = models.CharField(
        max_length=50, verbose_name=_('Nome do Tipo de Audiência Pública'), default='Audiência Pública')
    tipo = models.CharField(
        max_length=1, verbose_name=_('Tipo de Audiência Pública'), choices=TIPO_AUDIENCIA_CHOICES, default='A')


    class Meta:
        verbose_name = _('Tipo de Audiência Pública')
        verbose_name_plural = _('Tipos de Audiência Pública')
        ordering = ['nome']

    def __str__(self):
        return self.nome


@reversion.register()
class AudienciaPublica(models.Model):
    materia = models.ForeignKey(
        MateriaLegislativa,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_('Matéria Legislativa'))
    tipo = models.ForeignKey(TipoAudienciaPublica,
                             on_delete=models.PROTECT,
                             null=True,
                             blank=True,
                             verbose_name=_('Tipo de Audiência Pública'))
    numero = models.PositiveIntegerField(blank=True, verbose_name=_('Número'))
    nome = models.CharField(
        max_length=100, verbose_name=_('Nome da Audiência Pública'))
    tema = models.CharField(
        max_length=100, verbose_name=_('Tema da Audiência Pública'))
    data = models.DateField(verbose_name=_('Data'))
    hora_inicio = models.CharField(
        max_length=5, verbose_name=_('Horário Início(hh:mm)'))
    hora_fim = models.CharField(
        max_length=5, verbose_name=_('Horário Fim(hh:mm)'))
    observacao = models.TextField(
        max_length=500, blank=True, verbose_name=_('Observação'))
    audiencia_cancelada = models.BooleanField(
        default=False,
        choices=YES_NO_CHOICES,
        verbose_name=_('Audiência Cancelada?'))
    url_audio = models.URLField(
        max_length=150, blank=True,
        verbose_name=_('URL Arquivo Áudio (Formatos MP3 / AAC)'))
    url_video = models.URLField(
        max_length=150, blank=True,
        verbose_name=_('URL Arquivo Vídeo (Formatos MP4 / FLV / WebM)'))
    upload_pauta = models.FileField(
        blank=True,
        null=True,
        upload_to=pauta_upload_path,
        verbose_name=_('Pauta da Audiência Pública'),
        validators=[restringe_tipos_de_arquivo_txt])
    upload_ata = models.FileField(
        blank=True,
        null=True,
        upload_to=ata_upload_path,
        verbose_name=_('Ata da Audiência Pública'),
        validators=[restringe_tipos_de_arquivo_txt])
    upload_anexo = models.FileField(
        blank=True,
        null=True,
        upload_to=anexo_upload_path,
        verbose_name=_('Anexo da Audiência Pública'))

    class Meta:
        verbose_name = _('Audiência Pública')
        verbose_name_plural = _('Audiências Públicas')
        ordering = ['nome', 'numero', 'tipo']

    def __str__(self):
        return self.nome

    def delete(self, using=None, keep_parents=False):
        if self.upload_pauta:
            self.upload_pauta.delete()

        if self.upload_ata:
            self.upload_ata.delete()

        if self.upload_anexo:
            self.upload_anexo.delete()

        return models.Model.delete(
            self, using=using, keep_parents=keep_parents)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if not self.pk and (self.upload_pauta or self.upload_ata or
                            self.upload_anexo):
            upload_pauta = self.upload_pauta
            upload_ata = self.upload_ata
            upload_anexo = self.upload_anexo
            self.upload_pauta = None
            self.upload_ata = None
            self.upload_anexo = None
            models.Model.save(self, force_insert=force_insert,
                              force_update=force_update,
                              using=using,
                              update_fields=update_fields)

            self.upload_pauta = upload_pauta
            self.upload_ata = upload_ata
            self.upload_anexo = upload_anexo

        return models.Model.save(self, force_insert=force_insert,
                                 force_update=force_update,
                                 using=using,
                                 update_fields=update_fields)

sapl/relatorios/models.py
# from django.db import models

# Create your models here.

sapl/audiencia/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import transaction
from django.utils.translation import ugettext_lazy as _
from sapl.audiencia.models import AudienciaPublica, TipoAudienciaPublica
from sapl.materia.models import MateriaLegislativa, TipoMateriaLegislativa
from sapl.utils import timezone

class AudienciaForm(forms.ModelForm):

    data_atual = timezone.now()

    tipo = forms.ModelChoiceField(required=True,
                                  label='Tipo de Audiência Pública',
                                  queryset=TipoAudienciaPublica.objects.all().order_by('nome'))

    tipo_materia = forms.ModelChoiceField(
        label=_('Tipo Matéria'),
        required=True,
        queryset=TipoMateriaLegislativa.objects.all(),
        empty_label='Selecione',
    )

    numero_materia = forms.CharField(
        label='Número Matéria', required=True)

    ano_materia = forms.CharField(
        label='Ano Matéria',
        initial=int(data_atual.year),
        required=True)

    class Meta:
        model = AudienciaPublica
        fields = ['tipo', 'numero', 'nome',
                  'tema', 'data', 'hora_inicio', 'hora_fim',
                  'observacao', 'audiencia_cancelada', 'url_audio',
                  'url_video', 'upload_pauta', 'upload_ata',
                  'upload_anexo', 'tipo_materia', 'numero_materia',
                  'ano_materia']


    def __init__(self, **kwargs):
        super(AudienciaForm, self).__init__(**kwargs)

        tipos = []

        if not self.fields['tipo'].queryset:
            tipos.append(TipoAudienciaPublica.objects.create(nome='Audiência Pública', tipo='A'))
            tipos.append(TipoAudienciaPublica.objects.create(nome='Plebiscito', tipo='P'))
            tipos.append(TipoAudienciaPublica.objects.create(nome='Referendo', tipo='R'))
            tipos.append(TipoAudienciaPublica.objects.create(nome='Iniciativa Popular', tipo='I'))

            for t in tipos:
                t.save()


    def clean(self):
        cleaned_data = super(AudienciaForm, self).clean()
        if not self.is_valid():
            return cleaned_data

        try:
            materia = MateriaLegislativa.objects.get(
                numero=self.cleaned_data['numero_materia'],
                ano=self.cleaned_data['ano_materia'],
                tipo=self.cleaned_data['tipo_materia'])
        except ObjectDoesNotExist:
            msg = _('A matéria a ser inclusa não existe no cadastro'
                    ' de matérias legislativas.')
            raise ValidationError(msg)
        else:
            cleaned_data['materia'] = materia

        if self.cleaned_data['hora_inicio'] and self.cleaned_data['hora_fim']:
            if (self.cleaned_data['hora_fim'] <
                self.cleaned_data['hora_inicio']):
                    msg = _('A hora de fim não pode ser anterior a hora de ínicio')
                    raise ValidationError(msg)

        return self.cleaned_data

    @transaction.atomic()
    def save(self, commit=True):
        audiencia = super(AudienciaForm, self).save(commit)
        return audiencia

sapl/templates/base/RelatorioAtas_filter.html
{% extends "crud/list.html" %}
{% load i18n %}
{% load crispy_forms_tags staticfiles %}

{% block base_content %}
  {% if not filter_url %}
    {% crispy filter.form %}
  {% endif %}

  {% if filter_url %}
    <div class="actions btn-group pull-right" role="group">
      <a href="{% url 'sapl.base:atas' %}" class="btn btn-default">{% trans 'Fazer nova pesquisa' %}</a>
    </div>
    <br /><br /><br />
    {% if object_list|length > 0 %}
      <table class="table table-striped table-hover">
    	  <thead>
    	    <tr>
    				<th>Sessão</th>
    				<th>Ata</th>
    	    </tr>
    	  </thead>
    	  <tbody>
    			{% for sessao in object_list %}
    				<tr>
    					<td>{{sessao}}</td>
    					<td><a href="{{ sessao.upload_ata.url }}">
    						<img src="{% static 'img/file.png' %}">
    					</a></td>
    				</tr>
    			{% endfor %}
    	  </tbody>
    	</table>
    {% else %}
      <font size="5"><p align="center">Nenhum sessão com ata foi encontrada!</p></font>
    {% endif %}
  {% endif %}
{% endblock base_content %}

sapl/templates/base/RelatorioHistoricoTramitacao_filter.html
{% extends "crud/list.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block base_content %}
  {% if not show_results %}
    {% crispy filter.form %}
  {% endif %}

  {% if show_results %}
    <div class="actions btn-group pull-right" role="group">
      <a href="{% url 'sapl.base:historico_tramitacoes' %}" class="btn btn-default">{% trans 'Fazer nova pesquisa' %}</a>
    </div>
    <br /><br /><br /><br />
    <table class="table table-bordered table-hover">
      <thead class="thead-default" >
        <tr class="active">
          <th>Matéria</th>
          <th>Ementa</th>
        </tr>
      </thead>
      <tbody>
        {% for materia in object_list %}
          <tr>
            <td><a href="{% url 'sapl.materia:tramitacao_list' materia.pk %}">
              {{materia.tipo.descricao}} - {{materia.tipo.sigla}} {{materia.numero}}/{{materia.ano}}
            </a></td>
            <td>{{materia.ementa}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}
{% endblock base_content %}

sapl/templates/base/RelatorioMateriasPorAnoAutorTipo_filter.html
{% extends "crud/list.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block base_content %}
  {% if not show_results %}
    {% crispy filter.form %}
  {% endif %}

  {% if show_results %}
    <div class="actions btn-group pull-right" role="group">
      <a href="{% url 'sapl.base:materia_por_ano_autor_tipo' %}" class="btn btn-default">{% trans 'Fazer nova pesquisa' %}</a>
    </div>
    <br /><br /><br /><br />

    {% for r in relatorio %}
       <h3>{{r.autor}}</h3><br/>
       <table class="table table-bordered table-hover">
         <thead class="thead-default" >
           <tr class="active">
             <th>Natureza da Propositura</th>
             <th>Quantidade</th>
           </tr>
         </thead>
         <tbody>
           {% for i in r.materia %}
             <tr>
               <td>{{i.0}}</td><td>{{i.1}}</td>
             </tr>
           {% endfor %}
         </tbody>
       </table>
       <h3>Total: {{r.total}}</h3><br/>
       <br/>
       <br/>
    {% endfor %}
    <br/><br/>

    <table class="table table-bordered table-hover">
      <thead class="thead-default" >
        <tr class="active"><th colspan="2" class="text-center">QUADRO GERAL</th></tr>
        <tr class="active">
          <th>Tipo Matéria</th>
          <th>Quantidade</th>
        </tr>
      </thead>
      <tbody>
        {% for key, value in qtdes.items %}
          <tr>
            <td>{{key.sigla}} - {{key}}</td>
            <td>{{value}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

{% endblock base_content %}

sapl/templates/base/alterar_senha.html
{% extends "crud/detail.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block actions %}{% endblock %}
{% block detail_content %}
    <h1>Alterar Senha</h1>
	{% crispy form %}
    </br>
    Atenção, a mudança de senha fará com que o usuário atual seja deslogado do sistema.</br>
    Favor entrar novamente com a nova senha após a mudança com sucesso.

{% endblock detail_content %}

sapl/templates/base/autor_form.html
{% extends "crud/form.html" %}
{% load i18n %}
{% block extra_js %}

<script type="text/javascript">

$(document).ready(function(){
  var flag_create = false;
  if (location.href.indexOf('create') > 0) {
    $('.radiogroup-status').remove();
    flag_create = true
  }
  var active = function(str, atualizar=true) {
    if (str == 'nome') {
      if (atualizar)
        $('#id_nome, #id_q, #id_cargo').val('');
      $('.div_nome_cargo').removeClass('hidden');
      $("#div_id_autor_related .controls").html('');
      $("[data-application='AutorSearch'], .radiogroup-autor-related").addClass('hidden');
    }
    else {
      $('#id_nome, #id_cargo').val('');
      $('.div_nome_cargo').addClass('hidden');
      $("#div_id_autor_related .alert").remove();
      $("[data-application='AutorSearch'], .radiogroup-autor-related").removeClass('hidden');
    }
  }
  var update_search = function(pk, atualizar=true) {
    var q = $('#id_q').val();

    var url = '{% url 'sapl.api:autores_provaveis_list'%}'

    var formData = {
          'q'         : q,
          'tipo'      : pk
    }
    $.get(url, formData).done(function(data) {
        active('pesquisa');
        if (atualizar) {
          var radios = $("#div_id_autor_related .controls").html('');
          data.results.forEach(function (val, index) {
            var html_radio = '<div class="radio"><label><span class="icons"><span class="first-icon"></span><span class="second-icon"></span></span><input type="radio" name="autor_related" id="id_autor_related_'+index+'" value="'+val.value+'" style="display:none;">'+val.text+'</label></div>';
            radios.append(html_radio);
          });

          if (data.results.length > 1) {
            $('input[name=autor_related]').change(function(event){
              if (this.checked)
                $('#id_q').val(event.target.parentElement.textContent);
              //$('input[name=autor_related]:not(:checked)').closest('.radio').remove();
            });
          }
          else {
            $('input[name=autor_related]').prop('checked', 'checked');
            $('input[name=autor_related]').closest('.radio').addClass('checked');
          }

          if (data.pagination.total_entries > 10)
            radios.before('<div class="alert alert-info" role="alert"><strong>{% trans "Foram encontrados" %} '+data.pagination.total_entries+' {% trans "registros"%}</strong>'+' {% trans "mas será mostrado apenas os 10 primeiros resultados. Coloque mais informações no campo pesquisa para refinar sua busca."%}</div>');
          else if (data.pagination.total_entries == 0)
            radios.before('<div class="alert alert-info" role="alert"><strong>{% trans "Não foram encontrados registros com os termos de pesquisa informados." %}</div>');
        }
        else{
          $('#id_nome, #id_q').val('');
          if ($('input[name=autor_related]').length == 1 ) {
            $('input[name=autor_related]').prop('checked', 'checked');
            $('input[name=autor_related]').closest('.radio').addClass('checked');
          }
        }
      }).fail(function(data) {
        active('nome', atualizar);
      });
  }

  $('#id_tipo').change(function(event) {
    if (event.target.selectedIndex == 0) {
      $('#id_nome, #id_q').val('');
      active('nome');
    }
    else {
      var pk = this[event.target.selectedIndex].value;
      $('input[name=autor_related]').closest('.radio').remove();
      update_search(pk, false)
    }
  });

  $('.btn-filtrar-autor').click(function(event) {
    var pk = $('#id_tipo').val();
    update_search(pk);
  });

  $('input[name=action_user]').change(function(event) {
    if (!this.checked)
      return;

    $('#div_id_username input').prop('readonly', '');

    if (event.target.value == 'N') {
      $('.new_user_fields').addClass('hidden');
      if ($('input[name=username]').attr('data') != '')
        $('.radiogroup-status').removeClass('hidden');

      if (flag_create) {
        $('#div_id_username').addClass('hidden');
      }
      else {
        $('#div_id_username input').prop('readonly', 'readonly');
      }
    }
    else {
      $('.radiogroup-status').addClass('hidden');
      $('#div_id_username').removeClass('hidden');
      $('.new_user_fields').addClass('hidden');
    }
    if (!flag_create) {
      var username = $('input[name=username]');
      if (username.length == 1) {
        if ((event.target.value == 'A' && username.attr('data') != '' && username[0].value != username.attr('data'))
            || (event.target.value == 'C' && username.attr('data') != ''))
          $('.radiogroup-status').removeClass('hidden');
      }
    }
  });

  $('input[name=username]').keyup(function(event) {
    if (!flag_create)
      if (this.getAttribute('data') != '' && this.value != this.getAttribute('data'))
        $('.radiogroup-status').removeClass('hidden');
      else
          $('.radiogroup-status').addClass('hidden');
  });

  $('input[name=action_user]:checked').trigger('change');
  if (flag_create)
    $('input[name=autor_related]').closest('.radio').remove();

  var pk = $('#id_tipo').val();
  if (pk)
    update_search(pk, $('#id_q').val().length > 0)

});


</script>

{% endblock %}

sapl/templates/base/recuperar_senha_completo.html
{% extends "crud/detail.html" %}

{% block table_content %}
A sua senha foi alterada com sucesso! Clique <a href="{% url 'sapl.base:login' %}">aqui</a> e faça seu login.
{% endblock %}

sapl/templates/base/recuperar_senha_email_form.html
{% extends "crud/form.html" %}